name: DjangoComprobaciones

on:
  push:
    branches: [ "desarrollo" ]
  pull_request:
    branches: [ "desarrollo" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10, 3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test about
        python manage.py test autenticacion
        python manage.py test contacto
        python manage.py test home
        python manage.py test pedidos
        python manage.py test tienda
        python manage.py test
        
